### ISSUE TITLE
Connection drops as the cockpit session times out

### ISSUE THREAD

**Issue by intelliant01** [cyberorg/assist-cockpit#5]
Need to explore an option to override / increase cockpit session timeout due to inactivity or give an alert to the user to extend session.

**Comment by cyberorg** [comment]
There is already countdown timer and a popup.

However this should be filed upstream if anything additional is needed.

**Comment by intelliant01** [comment]
Countdown timer never alerted.

Have opted for this in `/etc/cockpit/cockpit.conf` that disables the session timeout. 

```
[Session]
IdleTimeout=0
```

May close.
